import type { UserStats } from './db';
import { Sword, Wand, Music, Hammer, Scroll, Coins, User, Shield, Book, Mic, Wrench, Sun, Gem, Crown, Zap, Star, Lightbulb, Eye, Landmark } from 'lucide-react';

export interface CharacterClass {
    id: string;
    name: string;
    description: string;
    requirement: (stats: UserStats) => boolean;
    uiRequirement: string;
    icon: any;
    color: string;
    borderColor: string;
    bgGradient: string;
}

export const CLASSES: CharacterClass[] = [
    {
        id: 'novice',
        name: 'Novice',
        description: 'The beginning of every journey.',
        requirement: () => true, // Always unlocked
        uiRequirement: 'None',
        icon: User,
        color: 'text-gray-400',
        borderColor: 'border-gray-500',
        bgGradient: 'from-gray-800 to-gray-900',
    },
    {
        id: 'squire',
        name: 'Squire',
        description: 'A warrior in training, establishing their strength.',
        requirement: (stats) => stats.strength >= 30,
        uiRequirement: 'Strength 30+',
        icon: Shield,
        color: 'text-red-300',
        borderColor: 'border-red-400',
        bgGradient: 'from-red-800 to-red-900',
    },
    {
        id: 'scholar',
        name: 'Scholar',
        description: 'A dedicated student seeking knowledge.',
        requirement: (stats) => stats.intelligence >= 30,
        uiRequirement: 'Intelligence 30+',
        icon: Book,
        color: 'text-blue-300',
        borderColor: 'border-blue-400',
        bgGradient: 'from-blue-800 to-blue-900',
    },
    {
        id: 'performer',
        name: 'Performer',
        description: 'An entertainer learning to capture hearts and minds.',
        requirement: (stats) => stats.charisma >= 30,
        uiRequirement: 'Charisma 30+',
        icon: Mic,
        color: 'text-pink-300',
        borderColor: 'border-pink-400',
        bgGradient: 'from-pink-800 to-pink-900',
    },
    {
        id: 'tinkerer',
        name: 'Tinkerer',
        description: 'A curious soul who builds understanding through creation.',
        requirement: (stats) => stats.creativity >= 30,
        uiRequirement: 'Creativity 30+',
        icon: Wrench,
        color: 'text-orange-300',
        borderColor: 'border-orange-400',
        bgGradient: 'from-orange-800 to-orange-900',
    },
    {
        id: 'acolyte',
        name: 'Acolyte',
        description: 'A devoted seeker of wisdom and truth.',
        requirement: (stats) => stats.wisdom >= 30,
        uiRequirement: 'Wisdom 30+',
        icon: Sun,
        color: 'text-green-300',
        borderColor: 'border-green-400',
        bgGradient: 'from-green-800 to-green-900',
    },
    {
        id: 'peddler',
        name: 'Peddler',
        description: 'A small-time trader understanding value.',
        requirement: (stats) => stats.wealth >= 30,
        uiRequirement: 'Wealth 30+',
        icon: Gem,
        color: 'text-yellow-300',
        borderColor: 'border-yellow-400',
        bgGradient: 'from-yellow-800 to-yellow-900',
    },
    {
        id: 'warrior',
        name: 'Warrior',
        description: 'A master of combat and physical prowess.',
        requirement: (stats) => stats.strength >= 50,
        uiRequirement: 'Strength 50+',
        icon: Sword,
        color: 'text-red-400',
        borderColor: 'border-red-500',
        bgGradient: 'from-red-900 to-red-950',
    },
    {
        id: 'mage',
        name: 'Mage',
        description: 'A scholar of arcane arts and intelligence.',
        requirement: (stats) => stats.intelligence >= 50,
        uiRequirement: 'Intelligence 50+',
        icon: Wand,
        color: 'text-blue-400',
        borderColor: 'border-blue-500',
        bgGradient: 'from-blue-900 to-blue-950',
    },
    {
        id: 'bard',
        name: 'Bard',
        description: 'A charmer who weaves magic through words and music.',
        requirement: (stats) => stats.charisma >= 50,
        uiRequirement: 'Charisma 50+',
        icon: Music,
        color: 'text-pink-400',
        borderColor: 'border-pink-500',
        bgGradient: 'from-pink-900 to-pink-950',
    },
    {
        id: 'artificer',
        name: 'Artificer',
        description: 'An inventor who creates wonders from imagination.',
        requirement: (stats) => stats.creativity >= 50,
        uiRequirement: 'Creativity 50+',
        icon: Hammer,
        color: 'text-orange-400',
        borderColor: 'border-orange-500',
        bgGradient: 'from-orange-900 to-orange-950',
    },
    {
        id: 'cleric',
        name: 'Cleric',
        description: 'A wise guardian who heals and protects.',
        requirement: (stats) => stats.wisdom >= 50,
        uiRequirement: 'Wisdom 50+',
        icon: Scroll,
        color: 'text-green-400',
        borderColor: 'border-green-500',
        bgGradient: 'from-green-900 to-green-950',
    },
    {
        id: 'merchant',
        name: 'Merchant',
        description: 'A shrewd negotiator who understands the value of everything.',
        requirement: (stats) => stats.wealth >= 50, // Assuming wealth is a stat like the others
        uiRequirement: 'Wealth 50+',
        icon: Coins,
        color: 'text-yellow-400',
        borderColor: 'border-yellow-500',
        bgGradient: 'from-yellow-900 to-yellow-950',
    },
    {
        id: 'warlord',
        name: 'Warlord',
        description: 'A legendary conqueror who rules the battlefield.',
        requirement: (stats) => stats.strength >= 99,
        uiRequirement: 'Strength 99+',
        icon: Crown,
        color: 'text-red-500',
        borderColor: 'border-red-600',
        bgGradient: 'from-red-950 to-black',
    },
    {
        id: 'archmage',
        name: 'Archmage',
        description: 'A supreme wielder of arcane secrets and cosmic truths.',
        requirement: (stats) => stats.intelligence >= 99,
        uiRequirement: 'Intelligence 99+',
        icon: Zap,
        color: 'text-blue-500',
        borderColor: 'border-blue-600',
        bgGradient: 'from-blue-950 to-black',
    },
    {
        id: 'virtuoso',
        name: 'Virtuoso',
        description: 'A world-renowned icon whose legacy is eternal.',
        requirement: (stats) => stats.charisma >= 99,
        uiRequirement: 'Charisma 99+',
        icon: Star,
        color: 'text-pink-500',
        borderColor: 'border-pink-600',
        bgGradient: 'from-pink-950 to-black',
    },
    {
        id: 'visionary',
        name: 'Visionary',
        description: 'A genius who reshapes reality with their ideas.',
        requirement: (stats) => stats.creativity >= 99,
        uiRequirement: 'Creativity 99+',
        icon: Lightbulb,
        color: 'text-orange-500',
        borderColor: 'border-orange-600',
        bgGradient: 'from-orange-950 to-black',
    },
    {
        id: 'prophet',
        name: 'Prophet',
        description: 'A divine messenger who sees the threads of fate.',
        requirement: (stats) => stats.wisdom >= 99,
        uiRequirement: 'Wisdom 99+',
        icon: Eye,
        color: 'text-green-500',
        borderColor: 'border-green-600',
        bgGradient: 'from-green-950 to-black',
    },
    {
        id: 'tycoon',
        name: 'Tycoon',
        description: 'A master of empires whose wealth knows no bounds.',
        requirement: (stats) => stats.wealth >= 99,
        uiRequirement: 'Wealth 99+',
        icon: Landmark,
        color: 'text-yellow-500',
        borderColor: 'border-yellow-600',
        bgGradient: 'from-yellow-950 to-black',
    }
];

export const getClassConfig = (classId: string | undefined): CharacterClass => {
    return CLASSES.find(c => c.id === classId) || CLASSES[0];
};
